name: Update Economic News

on:
  schedule:
    - cron: "*/30 * * * *"   # tiap 30 menit
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python scripts/fetch.py

      - name: Commit update
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add data/news.json
          git commit -m "update news" || echo "no changes"
          git push
